site_name: Termo em haskell
site_url: https://unbparadigmas2024-1.github.io/2024.1_G4_Funcional_Termo/

nav:
    - Home: index.md
    - Sobre: about.md
    - Instalação: instalacao.md
    - Resultados Finais: resultados-finais.md
    - Participações: participacoes.md
theme:
  name: material